COUNTRIES = [
    "Worldwide - world",
    "United States - us",
    "United Kingdom - gb",
    "Canada - ca",
    "Australia - au",
    "Germany - de",
    "France - fr",
    "Spain - es",
    "Italy - it",
    "Netherlands - nl",
    "Brazil - br",
    "Japan - jp",
    "India - in",
    "China - cn",
    "Russia - ru",
    "Mexico - mx",
    "Argentina - ar",
    "South Korea - kr",
    "Indonesia - id",
    "Turkey - tr",
    "Saudi Arabia - sa",
    "South Africa - za",
    "Nigeria - ng",
    "Egypt - eg",
    "Pakistan - pk",
    "Thailand - th",
    "Vietnam - vn",
    "Philippines - ph",
    "Malaysia - my",
    "Singapore - sg",
    "Israel - il",
    "United Arab Emirates - ae",
    "Poland - pl",
    "Sweden - se",
    "Norway - no",
    "Denmark - dk",
    "Finland - fi",
    "Ireland - ie",
    "Belgium - be",
    "Switzerland - ch",
    "Austria - at",
    "Greece - gr",
    "Portugal - pt",
    "Czech Republic - cz",
    "Hungary - hu",
    "Romania - ro",
    "Ukraine - ua",
    "Bulgaria - bg",
    "Croatia - hr",
    "Slovakia - sk",
    "Slovenia - si"
] 